# Generated by Django 3.1 on 2020-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flight', models.ManyToManyField(blank=True, related_name='passenger', to='flights.Flight')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
